### DISCUSSION TITLE
Be more specific saying that a PWA is installable

### DISCUSSION THREAD

**Discussion by davidromani** [Spomky-Labs/pwa-bundle#100] [Ideas]
Maybe if someone arrived to this bundle is not so obvious that when we talk about doing a web app built with Symfony installable, may be needs to be more precise saying that it's only installable for the mobile device browsers (aka smatphones or tablets).

If you try to do a PWA installation with a desktop browser the whole process it doesn't works, maybe it seems to obvious, or maybe not... In my opinion is better to write in the documentation this _subtle_ information.

**Comment by Spomky** [comment]
It can be installed on desktop browser. Safari is the only exception and things are "complicated".
I will write the missing section

**Reply by tacman** [reply]
Go to https://noise.survos.com -- it can be installed on the desktop.  (Work in progress, it's a test project for a bootstrap-based PWA).

Repo at https://github.com/survos-sites/noise

My goal is to make it work at a 100% standalone app after installation.

**Comment by davidromani** [comment]
I've tried to install with Safari, Firefox & Chorme (both of them with desktop versions) on my macOS and never seen the button to install. 

I've cheched my manifest.json and it seems to be ok. I've remove caches from Symfony & browser too and I'm **not** trying to install from a private (incognito) browser window.

**Comment by Spomky** [comment]
You don't have anything [like in here](https://github.com/symfony/ux/pull/1350#issue-2053883207)?

**Reply by davidromani** [reply]
No 🤷‍♂️

**Comment by davidromani** [comment]
@Spomky would you like to see my manifest file?

**Reply by Spomky** [reply]
Yes please. Or go to the debug window and capture the application warnings.
To be installed, some properties are mandatory. Maybe one is missing or invalid

**Reply by davidromani** [reply]
All this code has been applied into a brand new Symfony demo [clone](https://github.com/symfony/demo) (v2.5.1) only for testing purpouses:

```yaml
# config/packages/pwa.yaml
pwa:
    manifest:
        enabled: true
        id: '/'
        scope: '/'
        name: 'Symfony Demo PWA'
        short_name: 'SF PWA'
        start_url: '/ca'     # 'ca' Catalan is my default locale
        display: 'standalone'
        background_color: '#ffffff'
        theme_color: '#4285f4'
    serviceworker:
        enabled: true
        src: 'sw.js'
        workbox:
            enabled: true
```

```twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="view-transition" content="same-origin" />
        <title>{% block title %}Symfony Demo application{% endblock %}</title>
        <link rel="alternate" type="application/rss+xml" title="{{ 'rss.title'|trans }}" href="{{ path('blog_rss') }}">
        {% block stylesheets %}{% endblock %}
        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
        <link rel="shortcut icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
        {{ pwa() }} {# here, before close the head node, is where I've put the PWA bundle Twig command #}
    </head>
    <body id="{% block body_id %}{% endblock %}">
        ...
```
```bash
$ composer show spomky-labs/pwa-bundle
name     : spomky-labs/pwa-bundle
descrip. : Progressive Web App Manifest Generator Bundle for Symfony.
keywords : bundle, pwa, symfony
versions : * 1.0.5
```
```
# /site.webmanifest
{
    "categories": [],
    "name": "Symfony Demo PWA",
    "short_name": "SF PWA",
    "start_url": "/ca",
    "background_color": "#ffffff",
    "display": "standalone",
    "display_override": [],
    "id": "/",
    "scope": "/",
    "theme_color": "#4285f4",
    "scope_extensions": [],
    "icons": [],
    "screenshots": [],
    "file_handlers": [],
    "protocol_handlers": [],
    "related_applications": [],
    "shortcuts": [],
    "widgets": []
}
```
<img width="934" alt="Captura de pantalla 2024-03-06 a les 12 42 24" src="https://github.com/Spomky-Labs/pwa-bundle/assets/698779/fe221789-1d0d-46d7-983b-07055eeabcdd">
