### DISCUSSION TITLE
How to exclude cached assets from /assets/bundles/*

### DISCUSSION THREAD

**Discussion by davidromani** [Spomky-Labs/pwa-bundle#109] [Q&A] [answered]
How can I prevent that all the assets installed inside `/assets/bundle` (and subdirectories) will be cached?

<img width="1719" alt="Captura de pantalla 2024-03-07 a les 9 21 50" src="https://github.com/Spomky-Labs/pwa-bundle/assets/698779/6b7be531-2264-47dd-9d66-5a8ad89a4a25">

This kind of assets I only use in backend admin section, and I don't want to have cached with my Service Worker.

My PWA config package is:

```yaml
pwa:
    manifest:
        enabled: true
        name: '%project_web_title% PWA'
        id: '/'
        scope: '/'
        short_name: '%project_web_title%'
        start_url: '/'
        display: 'standalone'
        background_color: '#ffffff'
        theme_color: '#4285f4'
    serviceworker:
        enabled: true
        src: 'sw.js'
        workbox:
            enabled: true
            network_timeout_seconds: 2
            static_regex: '/\.(css|jsx?)$/'
            warm_cache_urls:
                - path: 'app_frontend_homepage'
                  params:
                      _locale: 'ca'
                - path: 'app_frontend_homepage'
                  params:
                      _locale: 'es'
                - path: 'app_frontend_homepage'
                  params:
                      _locale: 'en'
                - path: 'app_frontend_homepage'
                  params:
                      _locale: 'fr'
                - path: 'app_offline_fallback'
            page_fallback: 'app_offline_fallback'
```

**Comment by Spomky** [comment]
Hi,

You can change the `static_regex` option and exclude the folder `bundle`.
I am not a regex master, but something like `(?!\/bundle\/).*\.(css|jsx?)$` should be fine.
`(?!\/bundle\/).*` says that if the string contains /bundle/, it should be excluded.

**Reply by Spomky** [reply]
Or this one: `^(?!\/assets\/bundle\/).*\.(css|jsx?)$` to be more precise and exclude all strating with `/assets/bundles/*`
You may have `/assets/@symfony/bundle/*` that could be captured with my previous answer

**Reply by Spomky** [reply]
![2024-03-07_11h12_06](https://github.com/Spomky-Labs/pwa-bundle/assets/1091072/031eb2e7-0520-4c03-a3ff-28e5202d7bc8)

**Reply by davidromani** [reply]
declared like this in config/packages/pwa.yaml?

```yaml
static_regex: '/^(?!\/assets\/bundle\/).*\.(css|jsx?)$/'
```

**Reply by Spomky** [reply]
Yes

**Comment by davidromani** [comment]
It seems that the regex expression does **not** works, just opened the project in another computer (fresh Service Worker installation) and I could see those assets (`/assets/bundle/...`) still cached.

![Captura de pantalla 2024-03-07 a les 18 51 34](https://github.com/Spomky-Labs/pwa-bundle/assets/698779/1f53d9dc-a418-45bf-8ec7-ad0b088cff50)

**Comment by Spomky** [comment]
Typo: bundle**s** instead of bundle

**Comment by davidromani** [comment]
Hi again.

When I started this discussion I was using an older version (less than 1.1.4) of `spomky-labs/pwa-bundle`. Now, I've realised that with the new bundle configuration rules I'm facing again the same problem.

The inclusion of all the assets installed inside `/assets/bundle` (and subdirectories) has been appeared again. I suspect the it's a problem with my current `pwa.yaml` configuration becasue I'm using the old format to declare how to cache the assets...

Can you help me (again) to solve the same problem? Many thanks.

```yaml
# config/packages/pwa.yaml
pwa:
    image_processor: 'pwa.image_processor.gd'
    manifest:
        enabled: true
    serviceworker:
        enabled: true
        src: 'sw.js'
        workbox:
            enabled: true
            cache_manifest: true
            asset_cache:
                enabled: true
                regex: '/^(?!\/assets\/bundles\/).*\.(css|jsx?|ico|png|jpe?g|gif|svg|webp)$/'
            resource_caches:
                -
                    match_callback: 'startsWith: /'
                    cache_name: 'static-pages'
                    strategy: 'NetworkFirst'
                    network_timeout: 1
                    preload_urls:
                        -
                            path: 'app_frontend_homepage'
                            params:
                                _locale: 'en'
```
