### DISCUSSION TITLE
How to test offline

### DISCUSSION THREAD

**Discussion by tacman** [Spomky-Labs/pwa-bundle#251] [Q&A]
I have an app at https://pokemon.survos.com/ which I want to run offline.  I've setup the offline page to app_index and preload it, but after loading (and installing) if I turn the network off and try to open the app, it says it's offline.  Running pwa-bundle:1.3.x

```yaml
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            resource_caches:
                - match_callback: 'navigate'
                  max_age: 365 days
                  max_entries: 200
                  preload_urls:
                      - 'app_index'
            offline_fallback:
                page: 'app_index'
```

When I test on my local computer (and not my phone), if I use the Chrome network tab to turn off the network, it seems to work sometimes.  But not if I actually turn my wifi off.

Source is at https://github.com/survos-sites/pokemon
